HTML Kitchen Sink Update
sparkdesignsystem/spark-starter-html pull request #24
Opened 2020-11-24 15:59 UTC by bobwise

2020-11-24 16:40 UTC, afebbraro commented on src/styles/navigation.scss
> +.#{$app-namespace}-c-AngularNav a:hover,
Lets update to not be "Angular".

2020-11-24 16:41 UTC, afebbraro requested changes
Let a comment about angular namespacing

2020-11-24 16:56 UTC, afebbraro approved these changes
Looks good, we'll want to wait to merge because of the pkg bump.

2020-12-04 19:54 UTC, bobwise commented
duplicate PR

2020-12-04 19:54 UTC, closed without merging